language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules
    - packages/**/node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script: npm run compile

    - stage: test
      name: "Lint & Typecheck"
      script: npm run check
    - script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      name: "Unit Test"

    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
